// Package transport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package transport

// SendRequest defines model for SendRequest.
type SendRequest struct {
	// Urls list of URLs
	Urls []string `json:"urls"`
}

// SendResponse defines model for SendResponse.
type SendResponse struct {
	Completed bool   `json:"completed"`
	Id        int    `json:"id"`
	Title     string `json:"title"`
	Url       string `json:"url"`
	UserId    int    `json:"userId"`
}

// SendResponseData defines model for SendResponseData.
type SendResponseData struct {
	Data []SendResponse `json:"data"`
}

// SendJSONRequestBody defines body for Send for application/json ContentType.
type SendJSONRequestBody = SendRequest
